#
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 100

Metrics/LineLength:
  Max: 150

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AlignHash:
  Enabled: false

Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
