#
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  TargetRubyVersion: 3.0.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*

Rails:
  Enabled: true

RSpec/FilePath:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 100

Layout/LineLength:
  Max: 500

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/requests/*
    - spec/system/*
    - spec/routing/*
    - spec/tasks/*

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
