# fly.toml file generated for panlexicon on 2022-06-16T19:48:12-07:00

app = "panlexicon"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RAILS_ENV = "production"
  RACK_ENV = "production"

[build]
  dockerfile = "Dockerfile.fly"

[deploy]
  release_command = "bin/rails db:prepare"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
