name: panlexicon
services:
- name: panlexicon
  environment_slug: ruby-on-rails
  github:
    branch: main
    deploy_on_push: true
    repo: bensheldon/panlexicon-rails
  run_command: bin/rails server -p $PORT -e ${RAILS_ENV:-production}

