defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>
  connect_timeout: 1
  checkout_timeout: 1

development:
  database: panlexicon_development
  <<: *defaults

test:
  database: panlexicon_test
  min_messages: WARNING
  <<: *defaults

staging:
  database: panlexicon_staging
  <<: *defaults

production:
  database: panlexicon_production
  <<: *defaults
  url:  <%= ENV["DATABASE_URL"] %>
  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '2s') %>