defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  connect_timeout: 1
  checkout_timeout: 1
  variables:
    statement_timeout: 2500 # ms

development:
  database: panlexicon_development
  <<: *defaults

test:
  database: panlexicon_test
  min_messages: WARNING
  <<: *defaults

staging:
  database: panlexicon_staging
  <<: *defaults

production:
  <<: *defaults
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
