name: Add to Backlog Project Board in Inbox
on: [issues, pull_request]

jobs:
  add_to_backlog:
    name: "Add to Backlog Project Board"
    runs-on: ubuntu-latest
    env:
      gh_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: 'Add Issue'
        if: ${{ github.event_name == 'issues' && env.gh_token }}
        uses: alex-page/github-project-automation-plus@9a05133789dbc96bd560ec84223a0ad49253d342
        with:
          project: Backlog
          column: Inbox
          repo-token: ${{ env.gh_token }}
      - name: "Add Pull Request"
        if: ${{ github.event_name == 'pull_request' && env.gh_token }}
        uses: alex-page/github-project-automation-plus@9a05133789dbc96bd560ec84223a0ad49253d342
        with:
          project: Backlog
          column: In progress
          repo-token: ${{ env.gh_token }}
