name: Add to Backlog Project Board in Inbox 

on: [issues, pull_request]

jobs:
  add-to-backlog-project-board:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.1
        if: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          project: Backlog
          column: Inbox
          repo-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
