name: Test and Deploy
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_FROZEN: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Ruby: Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Linters
        run: bin/lint --nofix

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: panlexicon
      RAILS_ENV: test
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_FROZEN: "true"

    services:
      postgres:
        image: "postgres:14"
        env:
          POSTGRES_USER: panlexicon
          POSTGRES_DB: panlexicon_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Dependencies
      - name: "Ruby: Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        run: bin/rails db:test:prepare
      - name: Compile assets
        run: bin/rails assets:precompile
      - name: Run tests
        run: RAILS_ENV=test DISABLE_SPRING=1 bin/rspec
      - name: Archive system spec screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots/

  deploy:
    name: "Deploy to Heroku"
    if: github.ref == 'refs/heads/main'
    needs: [test, lint]
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Push to Heroku
        run: |
          heroku git:remote -a panlexicon
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/panlexicon.git main:master
